version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "1111:1111"
    environment:
      DATABASE_FILE: ./flosscaster
      UPLOAD_PATH: ./uploads
      RSS_FILE: ./feed.xml
      FRONTEND_URL: ${FRONTEND_URL:-localhost:3000}

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
